name: Write to File

on:
  push:
    branches:
      - main

jobs:
  write-file:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Get last commit message
        id: last-commit
        run: echo "::set-output name=message::$(git log -1 --pretty=%B)"

      - name: Install Python dependencies
        if: contains(github.event.head_commit.message, '[skip ci]') == false
        run: |
          python -m pip install --upgrade pip
          pip install pylint bandit

      - name: Run pylint
        if: contains(github.event.head_commit.message, '[skip ci]') == false
        run: |
          pylint **/*.py > pylint-report.txt || true

      - name: Run bandit
        if: contains(github.event.head_commit.message, '[skip ci]') == false
        run: |
          bandit -r . -f txt -o bandit-report.txt

      - name: Commit changes
        if: contains(github.event.head_commit.message, '[skip ci]') == false
        run: |
          git config --global user.name 'Adwait Gawade'
          git config --global user.email 'adwaitg02@gmail.com'
          git add example.txt
          git commit -m "Add line of text to example.txt [skip ci]"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
